In [1]:
# ASSNP-02.py
# 2021-11-15
#
# 將" "分界改為"," ; 產生 dem-all-2.csv file
#
# run on myBinder.org JupyterLab
# 程式檔 path is '/home/jovyan/SSNP3D/2_dir'
# 資料檔 path is '/home/jovyan/SSNP3D/2_dir/data'
# 圖形檔 path is '/home/jovyan/SSNP3D/2_dir/graphic'
#
import os
path = os.getcwd()
print('當前工作目錄 ==>', path)
#
import csv
import numpy as np
import pprint
#
path_data    = './data/'
#
# 逐筆讀入資料 dem-all-1.grd (149328 row)
# Read from the file into the array data(:,:)
# array data shape is (149328, 3)
#
data1 = np.loadtxt(path_data + 'dem-all-1.grd',delimiter=' ',dtype='float')
#
i = 0
for row in data1 :
    i = i + 1
    # 顯示前五筆資料
    if i < 6 :
        pprint.pprint (row)
        for field in row :
            print (field)
        # end for
        print ('\n')
    # end if
# end for
#
float_To_int = np.vectorize(np.int32)
# Columns.
# data[..., 0] is array of float number
# data[..., 1] is array of float number
# data[..., 2] is array of float number
#
# for numpy -->  data[..., 1] 等價于 data[:, 1]
#
# 台灣橫麥卡托二度分帶投影座標系統（TM2）
#
TM2_X = float_To_int(data1[..., 0]) # 二度分帶 X座標
TM2_Y = float_To_int(data1[..., 1]) # 二度分帶 Y座標
TM2_Z = data1[..., 2]               # DEM file z value
#
i = 0
j = 0
for zValue in TM2_Z :
    i = i + 1
    # 顯示前五筆資料
    if i < 6 :
        print (zValue)
    # end if
    if zValue < 0 :
        j = j + 1
    # end if
# end for
#
print ('\n')
print (TM2_X.size) # 149328
print (TM2_Y.size) # 149328
print (TM2_Z.size) # 149328
print ('zValue < 0 筆數有',j)
print ('\n')
#
i = 0
dem_list = list(zip(TM2_X, TM2_Y, TM2_Z))
#
# 顯示前五筆資料
print (dem_list[0:5]) # begin at 0, total 5 items
print ('\n')
#
with open(path_data + 'dem-all-2.csv','wt', newline='', encoding='utf-8') as outfile :
    dem = csv.writer(outfile)
    dem.writerows(dem_list)
# end with    
#
print ('Done')

當前工作目錄 ==> /home/jovyan/SSNP3D/2_dir
array([1.75620e+05, 2.49994e+06, 3.94000e+00])
175620.0
2499940.0
3.94


array([1.75640e+05, 2.49994e+06, 5.28000e+00])
175640.0
2499940.0
5.28


array([1.75660e+05, 2.49994e+06, 5.92000e+00])
175660.0
2499940.0
5.92


array([1.75680e+05, 2.49994e+06, 2.25000e+00])
175680.0
2499940.0
2.25


array([1.75700e+05, 2.49994e+06, 2.95000e+00])
175700.0
2499940.0
2.95


3.94
5.28
5.92
2.25
2.95


149328
149328
149328
zValue < 0 筆數有 4882


[(175620, 2499940, 3.94), (175640, 2499940, 5.28), (175660, 2499940, 5.92), (175680, 2499940, 2.25), (175700, 2499940, 2.95)]


Done
