In [11]:
# SSNP-01.py
# 2021-11-14
#
# 將" "分界改為","; 調整高程數據 z --> 1.5*z; 產生dem-xx.csv file
#
# run on myBinder.org JupyterLab
# 程式檔 path is '/home/jovyan/SSNP3D/0_dir'
# 資料檔 path is '/home/jovyan/SSNP3D/0_dir/data'
# 圖形檔 path is '/home/jovyan/SSNP3D/0_dir/graphic'
#
import os
path = os.getcwd()
print('當前工作目錄 ==>', path)
#
import csv
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fontManager
#
from pprint import pprint
#
path_data    = './data/'
path_graphic = './graphic/'
read_file  = 'A-94182022dem.grd'
write_file = 'dem_94182022.csv'
#
# 逐筆讀入資料 2-94182052dem.grd (13247 row)
# Read from the file into the array data(:,:)
# array data shape is (13247, 3)
# 13247 rows, 3 columns
#
data_1 = np.loadtxt(path_data + read_file, delimiter=' ',dtype='float')
#
i = 0
for row in data_1 :
    i = i + 1
    # 顯示前五筆資料
    if i < 6 :
        print (row)
        for field in row :
            print (field)
        # end for
        print ('\n')
    # end if
# end for
#
print('---------------------')
#
function_float_convertTo_int = np.vectorize(np.int32)
#
# for numpy -->  data_1[..., 1] 等價于 data_1[:, 1]
#
# Columns.
# data_1[..., 0] is array of float number  # 二度分帶 X座標
# data_1[..., 1] is array of float number  # 二度分帶 Y座標
#
# 台灣橫麥卡托二度分帶投影座標系統（TM2）
#
TM2_X = function_float_convertTo_int(data_1[..., 0]) # 二度分帶 X座標
TM2_Y = function_float_convertTo_int(data_1[..., 1]) # 二度分帶 Y座標
TM2_Z = data_1[..., 2] # DEM file z value
#
j = 0
for zValue in TM2_Z :
    if zValue < 0 :
        j = j + 1
    # end if
# end for
#
print (TM2_X.size) # 13247
print (TM2_Y.size) # 13247
print (TM2_Z.size) # 13247
print ('zValue < 0 筆數有',j)
print('---------------------')
#
# round( x [, n]  )
#        x -- 數值表達式
#        n -- 表示從小數點位數
#
# 串列生成式
TM2_Z_list   = [round(z*1.5,2) for z in TM2_Z]
TM2_XYZ_list = list(zip(TM2_X,TM2_Y,TM2_Z_list))
i = 0
for item in TM2_XYZ_list :
    i = i + 1
    # 顯示前五筆資料
    if i < 6 :
        print (item)
    # end if
# end for
print('---------------------')
pprint(TM2_XYZ_list[0:5]) # begin at 0, total 5 items
print('---------------------')
#
with open(path_data + write_file,'wt') as outfile :
    dem = csv.writer(outfile)
    dem.writerows(TM2_XYZ_list)
# end with    
#
print ('Done')

當前工作目錄 ==> /home/jovyan/SSNP3D/0_dir
[1.76280e+05 2.50824e+06 1.01500e+01]
176280.0
2508240.0
10.15


[1.76300e+05 2.50824e+06 9.28000e+00]
176300.0
2508240.0
9.28


[1.76320e+05 2.50824e+06 1.06400e+01]
176320.0
2508240.0
10.64


[1.76340e+05 2.50824e+06 1.08100e+01]
176340.0
2508240.0
10.81


[1.76360e+05 2.50824e+06 1.08300e+01]
176360.0
2508240.0
10.83


---------------------
19296
19296
19296
zValue < 0 筆數有 0
---------------------
(176280, 2508240, 15.23)
(176300, 2508240, 13.92)
(176320, 2508240, 15.96)
(176340, 2508240, 16.22)
(176360, 2508240, 16.24)
---------------------
[(176280, 2508240, 15.23),
 (176300, 2508240, 13.92),
 (176320, 2508240, 15.96),
 (176340, 2508240, 16.22),
 (176360, 2508240, 16.24)]
---------------------
Done
