In [ ]:
# SSNP-01.py
# 2021-11-14
#
# 將" "分界改為","; 調整高程數據 z --> 1.5*z; 產生dem-xx.csv file
#
# run on mybinder.org
# 程式檔 path is './0_dir'
# 資料檔 path is './1_dir'
# 圖形檔 path is './2_dir'
#
import os
path = os.getcwd()
print('當前工作目錄 ==>', path)
#
import csv
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fontManager
#
from pprint import pprint
from mpl_toolkits.mplot3d import axes3d
#
def set_graphic_area(width,height) :
        
    cm2inch = 1/2.54    # inch per cm
    #
    # define graphic area
    #
    left_margin = 2.0   # cm
    right_margin = 2.0  # cm
    #
    figure_width  = width  # cm , from xmin to xmax
    figure_height = height # cm , from ymin to ymax
    #
    top_margin = 2.0    # cm
    bottom_margin = 2.0 # cm
    #
    box_width = left_margin + figure_width + right_margin   # cm
    box_height = top_margin + figure_height + bottom_margin # cm
    #
    top_value    = 1.0 - top_margin / box_height
    bottom_value = bottom_margin / box_height
    left_value   = left_margin / box_width
    right_value  = 1.0 - right_margin / box_width
    #
    return (box_width*cm2inch,box_height*cm2inch,top_value,bottom_value,left_value,right_value,width)
#
# end of def
#
matplotlib.rcParams['pdf.fonttype'] = 42
myfont = fontManager.FontProperties(fname='/home/jovyan/fonts/msjh.ttc')
# ----------------------------------------------------------------------
#
tup7 = set_graphic_area(30,30)
#
fig = plt.figure(figsize=(tup7[0], tup7[1]))
ax  = fig.add_subplot(1, 1, 1, projection='3d')
fig.subplots_adjust(
                top    = tup7[2] ,
                bottom = tup7[3] ,
                left   = tup7[4] ,
                right  = tup7[5] ,
                )
#
# plt.xlabel('X座標', fontproperties=myfont, fontsize=14)
# plt.ylabel('Y座標', fontproperties=myfont, fontsize=14)
ax.set_xlabel('X座標', fontproperties=myfont, fontsize=14)
ax.set_ylabel('Y座標', fontproperties=myfont, fontsize=14)
ax.set_zlabel('Z座標', fontproperties=myfont, fontsize=14)
#
path_data    = './data/'
path_graphic = './graphic/'
#
# 逐筆讀入資料 1-94182051dem.grd (13247 row)
# Read from the file into the array data(:,:)
# array data shape is (13247, 3)
# 13247 rows, 3 columns
#
data_1 = np.loadtxt(path_data + '2-94182052dem.grd',delimiter=' ',dtype='float')
#
# for numpy -->  data[..., 1] 等價于 data[:, 1]
#
i = 0
for row in data_1 :
    i = i + 1
    # 顯示前五筆資料
    if i < 6 :
        print (row)
        for field in row :
            print (field)
        # end for
        print ('\n')
    # end if
# end for
#
print('---------------------')
#
function_float_convertTo_int = np.vectorize(np.int32)
# Columns.
# data[..., 0] is array of float number  # 二度分帶 X座標
# data[..., 1] is array of float number  # 二度分帶 Y座標
#
# 台灣橫麥卡托二度分帶投影座標系統（TM2）
#
TM2_X = function_float_convertTo_int(data_1[..., 0]) # 二度分帶 X座標
TM2_Y = function_float_convertTo_int(data_1[..., 1]) # 二度分帶 Y座標
TM2_Z = data_1[..., 2] # DEM file z value
# round( x [, n]  )
#        x -- 數值表達式
#        n -- 表示從小數點位數
#
j = 0
for zValue in TM2_Z :
    if zValue < 0 :
        j = j + 1
    # end if
# end for
#
print (TM2_X.size) # 13247
print (TM2_Y.size) # 13247
print (TM2_Z.size) # 13247
print ('zValue < 0 筆數有',j)
print('---------------------')
#
# 串列生成式
TM2_Z_list   = [round(z*1.5,2) for z in TM2_Z]
TM2_XYZ_list = list(zip(TM2_X,TM2_Y,TM2_Z_list))
i = 0
for item in TM2_XYZ_list :
    i = i + 1
    # 顯示前五筆資料
    if i < 6 :
        print (item)
    # end if
# end for
print('---------------------')
pprint(TM2_XYZ_list[0:5]) # begin at 0, total 5 items
print('---------------------')
#
with open(path_data + 'dem-02.csv','wt') as outfile :
    dem_1 = csv.writer(outfile)
    dem_1.writerows(TM2_XYZ_list)
# end with    
#
# plot a 3D wireframe like in the example mplot3d/wire3d_demo
#
pprint(TM2_X[0:10])
pprint(TM2_Y[0:10])
tm2_z = np.array(list(TM2_Z), dtype='int32')
pprint(tm2_z[0:10])
#
# ax.plot_trisurf(TM2_X, TM2_Y, tm2_z, linewidth=0, antialiased=False)
#
xs, ys = np.meshgrid(TM2_X, TM2_Y)

# ax.plot_wireframe(xs, ys, zs, color='blue')
ax.plot_wireframe(xs, ys, tm2_z, rstride=2, cstride=2, color='blue')
#
# 設定子圖的標題
ax.set_title('台灣橫麥卡托二度分帶投影座標系統（TM2）', fontproperties=myfont, fontsize=18)
#
# bbox_inches='tight' is for display ylabel
# plt.savefig(path_graphic + "Hipparcos-02.png",format="png",dpi=72, bbox_inches='tight')
plt.savefig(path_graphic + "SSNP-01.pdf", dpi=300, bbox_inches='tight')
#
print ('Done')

當前工作目錄 ==> /home/jovyan/SSNP3D/0_dir
[1.76240e+05 2.49992e+06 1.75000e+00]
176240.0
2499920.0
1.75


[1.76260e+05 2.49992e+06 1.87000e+00]
176260.0
2499920.0
1.87


[1.76280e+05 2.49992e+06 1.97000e+00]
176280.0
2499920.0
1.97


[1.76300e+05 2.49992e+06 1.68000e+00]
176300.0
2499920.0
1.68


[1.76320e+05 2.49992e+06 1.52000e+00]
176320.0
2499920.0
1.52


---------------------
19296
19296
19296
zValue < 0 筆數有 407
---------------------
(176240, 2499920, 2.62)
(176260, 2499920, 2.8)
(176280, 2499920, 2.96)
(176300, 2499920, 2.52)
(176320, 2499920, 2.28)
---------------------
[(176240, 2499920, 2.62),
 (176260, 2499920, 2.8),
 (176280, 2499920, 2.96),
 (176300, 2499920, 2.52),
 (176320, 2499920, 2.28)]
---------------------
array([176240, 176260, 176280, 176300, 176320, 176340, 176360, 176380,
       176400, 176420], dtype=int32)
array([2499920, 2499920, 2499920, 2499920, 2499920, 2499920, 2499920,
       2499920, 2499920, 2499920], dtype=int32)
array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0], dtype=